# Labeler attributes
#   all: all changed files must match the list
#   any: any of changed files match the list

CI:
- any: ['.CI/**/*']
- any: ['.github/**/*']

p::DiscreteStateSpace:
- any: ['Modelica_LinearSystems2/DiscreteStateSpace.mo']

p::DiscreteTransferFunction:
- any: ['Modelica_LinearSystems2/DiscreteTransferFunction.mo']

p::DiscreteZerosAndPoles:
- any: ['Modelica_LinearSystems2/DiscreteZerosAndPoles.mo']

p::StateSpace:
- any: ['Modelica_LinearSystems2/StateSpace.mo']

p::TransferFunction:
- any: ['Modelica_LinearSystems2/TransferFunction.mo']

p::ZerosAndPoles:
- any: ['Modelica_LinearSystems2/ZerosAndPoles.mo']

p::Controllers:
- any: ['Modelica_LinearSystems2/Controller/**/*.mo']
- any: ['Modelica_LinearSystems2/Controllers/**/*.mo']

p::ComplexMathAdds:
- any: ['Modelica_LinearSystems2/ComplexMathAdds/**/*.mo']

p::Examples:
- all: ['Modelica_LinearSystems2/Examples/**/*.mo']

p::Internal:
- any: ['Modelica_LinearSystems2/Internal/**/*.mo']

p::Math:
- any: ['Modelica_LinearSystems2/Math/**/*.mo']
  all: ['!Modelica_LinearSystems2/Math/Complex.mo']
  all: ['!Modelica_LinearSystems2/Math/Polynomial.mo']

p::Math.Complex:
- all: ['Modelica_LinearSystems2/Math/Complex.mo']

p::Math.Polynomial:
- all: ['Modelica_LinearSystems2/Math/Polynomial.mo']

p::Records:
- any: ['Modelica_LinearSystems2/Records/**/*.mo']

p::Resources:
- all: ['Modelica_LinearSystems2/Resources/**/*']

p::Types:
- any: ['Modelica_LinearSystems2/Types/**/*.mo']

p::UsersGuide:
- all: ['Modelica_LinearSystems2/UsersGuide.mo']

p::Utilities:
- any: ['Modelica_LinearSystems2/Utilities/**/*.mo']


